
title: Golfcentrum Liberec
email: jiri.steiner@golfcentrumliberec.cz
description: >- # this means to ignore newlines until "baseurl:"
  FIXME
baseurl: "" # the subpath of your site, e.g. /blog
url: "new.golfcentrumliberec.cz" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
